account:
    aws_account_id: 783175685819
    aws_lambda_role: pywren_exec_role_1
    aws_region: us-west-2

lambda:
    memory : 1536
    timeout : 300
    function_name : pywren_1
    
s3:
    bucket: jonas-us-west-2
    pywren_prefix: pywren.jobs

runtime:
    s3_bucket:  pywren-public-us-west-2
    s3_key: pywren.runtimes/deep_gpu_3.6.meta.json

standalone:
    ec2_instance_type: p2.xlarge
    sqs_queue_name: pywren-jobs-1-solar
    visibility: 10
    ec2_ssh_key : ec2-us-west-2
    target_ami : ami-4c5ac82c
    instance_name: pywren-standalone-solar
    instance_profile_name: pywren-standalone-solar
    max_idle_time: 600
    idle_terminate_granularity: 3600
    availability_zone : us-west-2c
